
export const indianCities = [
  // North India
  'Delhi',
  'New Delhi',
  'Noida',
  'Gurgaon',
  'Faridabad',
  'Ghaziabad',
  'Chandigarh',
  'Amritsar',
  'Ludhiana',
  'Jalandhar',
  'Patiala',
  'Shimla',
  'Manali',
  'Dehradun',
  'Haridwar',
  'Rishikesh',
  'Nainital',
  'Mussoorie',
  'Agra',
  'Lucknow',
  'Kanpur',
  'Varanasi',
  'Allahabad',
  'Meerut',
  'Bareilly',
  'Aligarh',
  'Mathura',
  'Vrindavan',

  // Rajasthan
  'Jaipur',
  'Udaipur',
  'Jodhpur',
  'Jaisalmer',
  'Bikaner',
  'Ajmer',
  'Pushkar',
  'Mount Abu',
  'Kota',
  'Alwar',

  // West India
  'Mumbai',
  'Pune',
  'Nagpur',
  'Nashik',
  'Aurangabad',
  'Thane',
  'Navi Mumbai',
  'Kolhapur',
  'Lonavala',
  'Mahabaleshwar',
  'Ahmedabad',
  'Surat',
  'Vadodara',
  'Rajkot',
  'Gandhinagar',
  'Bhavnagar',
  'Jamnagar',
  'Dwarka',
  'Somnath',

  // South India
  'Bangalore',
  'Bengaluru',
  'Mysore',
  'Mangalore',
  'Coorg',
  'Hampi',
  'Hubli',
  'Chennai',
  'Coimbatore',
  'Madurai',
  'Pondicherry',
  'Ooty',
  'Kodaikanal',
  'Thanjavur',
  'Trichy',
  'Kanyakumari',
  'Hyderabad',
  'Secunderabad',
  'Vijayawada',
  'Visakhapatnam',
  'Tirupati',
  'Warangal',
  'Thiruvananthapuram',
  'Kochi',
  'Cochin',
  'Kovalam',
  'Alleppey',
  'Munnar',
  'Thekkady',
  'Wayanad',
  'Thrissur',
  'Kozhikode',
  'Calicut',
  'Kannur',

  // East India
  'Kolkata',
  'Darjeeling',
  'Siliguri',
  'Durgapur',
  'Asansol',
  'Howrah',
  'Bhubaneswar',
  'Puri',
  'Cuttack',
  'Konark',
  'Guwahati',
  'Shillong',
  'Gangtok',
  'Patna',
  'Gaya',
  'Bodh Gaya',
  'Ranchi',
  'Jamshedpur',

  // Goa
  'Goa',
  'Panaji',
  'Vasco da Gama',
  'Margao',
  'Mapusa',

  // Central India
  'Bhopal',
  'Indore',
  'Gwalior',
  'Jabalpur',
  'Ujjain',
  'Raipur',
  'Bilaspur',

  // Union Territories & Others
  'Port Blair',
  'Leh',
  'Ladakh',
  'Srinagar',
  'Jammu',
  'Puducherry',
];

// Top 30 most popular tourist/business cities (for your dropdown)
export const topIndianCities = [
  'Mumbai',
  'Delhi',
  'Bangalore',
  'Hyderabad',
  'Chennai',
  'Kolkata',
  'Pune',
  'Ahmedabad',
  'Jaipur',
  'Surat',
  'Lucknow',
  'Kanpur',
  'Nagpur',
  'Indore',
  'Thane',
  'Bhopal',
  'Visakhapatnam',
  'Vadodara',
  'Ghaziabad',
  'Ludhiana',
  'Agra',
  'Nashik',
  'Chandigarh',
  'Coimbatore',
  'Goa',
  'Kochi',
  'Mysore',
  'Udaipur',
  'Amritsar',
  'Varanasi',
];

export const indianCitiesAlphabetical = [...indianCities].sort();
